name: Build QField Plugin Package

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up directory structure
        run: |
          mkdir -p dist
      
      - name: Package Plugin
        run: |
          chmod +x scripts/package.sh
          ./scripts/package.sh
          cp transit-laser-plugin-1.0.0.zip dist/
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: transit-laser-plugin
          path: dist/transit-laser-plugin-1.0.0.zip
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/transit-laser-plugin-1.0.0.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}